---
Name: delectus-config
After:
  - 'framework/*'
---
Injector:
  TransportEncoding:
    class: DelectusJSONEncoding
  TransportEncryption:
    class: DelectusOpenSSLEncryption
  DelectusTransport:
    class: DelectusCURLTransport
    properties:
      encoder: %$TransportEncoding
      encrypter: %$TransportEncryption
  DelectusConfigModel:
    factory: DelectusCurrentSiteConfigFactory
DelectusModule:
  version: v1
  # Set to the client token you have been allocated, used to communicate with the delectus service
  # can be overriden in Delectus tab of CMS
  client_token: ''
  # Set to the client secret you have been assigned, used to secure information sent to the delectus service.
  # can be overriden in Delectus tab of CMS
  client_salt: ''
  # Set to the site id for the current site, used to communicate with the delectus service
  # can be overriden in Delectus tab of CMS
  site_identifier: ''
SiteConfig:
  delectus_fields_visible: true